"""add product table the base class has been changed

Revision ID: 65ceeaba6f04
Revises: 21e4eeff3bea
Create Date: 2024-05-07 14:22:49.961087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65ceeaba6f04'
down_revision: Union[str, None] = '21e4eeff3bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'registered_ad')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registered_ad', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_table('product')
    # ### end Alembic commands ###
